### ISSUE TITLE
Login: App is crashing while entering invalid key

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#302]
Not fixed, reporting new issue.

_Originally posted by @vikas1809 in https://github.com/ArcadeLabsInc/arcade/issues/278#issuecomment-1624932046_

**Comment by reyamir** [comment]
will fixed in this PR https://github.com/ArcadeLabsInc/arcade/pull/296

**Comment by vikas1809** [comment]
@reyamir  Still not fixed. Can you please reopen the ticket.

**Comment by earonesty** [comment]
ren i think we need to get rid of the reference on channels. loading them
does not seem to work with mobx state tree

**Comment by reyamir** [comment]
ah, in this case, app crash because poor handle error, which make app crash instead of return error message
```js
if (!nsec && nsec.length < 60) { alert("access key as nsec or hexstring is required") } else {...}
```
the alert in this case never work, then it will run code in `else`, and in `loginWithNsec` function we have 
```
if (!nsec.startsWith("nsec1") || nsec.length < 60) {
        return
}
```
`return` in this case will make app crash if private key invalid

in my latest PR https://github.com/ArcadeLabsInc/arcade/pull/351, I've fixed it by move all errors handler in MST to outside
```js
const login = () => {
    if (nsec.length < 60) {
      alert("Access key as nsec or hex private key is required")
    } else {
      setLoading(true)
      try {
        let privkey = nsec
        if (privkey.startsWith("nsec1")) {
          privkey = nip19.decode(privkey).data as string
        }
        const pubkey = getPublicKey(privkey)
        userStore.loginWithNsec(pool, mgr, privkey, pubkey)
      } catch {
        alert("Invalid key. Did you copy it correctly?")
        setLoading(false)
      }
    }
}
```
then we can notify user about error, and before send data to MST, we make sure all inputs are valid

I've also tesed fetch joined channels and it work fine now

Uploading Screen Recording 2023-07-12 at 10.50.17.mov…

**Comment by reyamir** [comment]
> ren i think we need to get rid of the reference on channels. loading them does not seem to work with mobx state tree

it work fine if I move `fetchJoinedChannels` outside MST, then pass joined channels list to `loginWithNsec`

```js
const ident = new ArcadeIdentity(privkey)
        pool.ident = ident

const joinedChannels = await userStore.fetchJoinedChannels(mgr)
joinedChannels.forEach((item) => {
          channelStore.create({
            id: item,
            author: "",
            privkey: "",
            name: "",
            about: "",
            picture: "",
            is_private: false,
          })
})

userStore.loginWithNsec(pool, ident, privkey, pubkey, joinedChannels)
```

I'm not sure why it not work if I place it in MST 🥲

**Comment by reyamir** [comment]
fixed in #366

**Comment by vikas1809** [comment]
Fixed, verified in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5618484429
