### ISSUE TITLE
Contacts: The Display image is missing for 'Suhail' on the Suggestions Page but after adding, the image displays on the Contacts

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#311]
"1. Open the Arcade app on Android
2. Tap on the 'Contact' icon and go to 'Add contact' screen by tapping the '+' icon
3. Scroll down the suggestions and notice no image appears for 'Suhail'
4. Add the contact and tap the back arrow to return the 'Contacts' screen
5. The Contact name 'Suhail' displays with image"

AR: The Display image is missing for 'Suhail' on the Suggestions Page but after adding, the image displays on the Contacts
ER: The Display image should appear everywhere for the registered contact
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMzM0OV8yMTcwMjc1NA

**Comment by reyamir** [comment]
fixed in latest commit

**Comment by vikas1809** [comment]
Still an issue, Verified in build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5583163026
![image](https://github.com/ArcadeLabsInc/arcade/assets/5452850/20320ffb-5997-400c-a61f-f0527bb7fee4)
![image](https://github.com/ArcadeLabsInc/arcade/assets/5452850/6e07a145-c5f9-4ea9-84ca-00e2bb38971d)
